#!/bin/bash

python /home/pi/iot-scripts/distance.py > /dev/null 2> /tmp/distance
DISTANCE_MM=$(</tmp/distance)
rm /tmp/distance

echo The distance is "$DISTANCE_MM"/mm

python3 /home/pi/iot-scripts/sendDistance.py Pi0 "$DISTANCE_MM"


